#!/bin/bash
# Deliberate, rare action (run by hand via `make refresh-base-image`, never
# automatically): downloads the CURRENT DietPi image for RPi 2/3/4 arm64
# trixie, verifies it against DietPi's own published sha256 + PGP
# signature, extracts its exact DietPi version (for the release tag), and
# re-publishes that exact verified blob as a GitHub Release asset on
# dhabensky/rpi-airplay -- since DietPi itself has no versioned archive
# (dietpi.com/downloads/images/ overwrites the same generic filename each
# release; confirmed via web research, and via their own community forum's
# repeated "where do I get an older version" threads). This establishes a
# stable, versioned, checksum-verifiable pin that routine builds
# (image-builder/fetch-base.sh) depend on instead of that mutable page.
#
# Requires: gh (authenticated: `gh auth login`), gpg.
set -euo pipefail
cd "$(dirname "$0")/.."

URL="https://dietpi.com/downloads/images/DietPi_RPi234-ARMv8-Trixie.img.xz"
KEYRING_URL="https://github.com/MichaIng.gpg"
REPO="dhabensky/rpi-airplay"

if ! command -v gh >/dev/null; then
  echo "ERROR: gh (GitHub CLI) is required to publish a release asset." >&2
  echo "  brew install gh && gh auth login" >&2
  exit 1
fi
gh auth status >/dev/null || { echo "ERROR: gh is not authenticated -- run 'gh auth login'" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

echo "==> Downloading $URL"
curl -sSL -o "$work/dietpi.img.xz" "$URL"
curl -sSL -o "$work/dietpi.img.xz.sha256" "$URL.sha256"
curl -sSL -o "$work/dietpi.img.xz.asc" "$URL.asc" || echo "  (no .asc signature published for this image, sha256-only)"

echo "==> Verifying sha256"
( cd "$work" && sha256sum -c <(awk '{print $1"  dietpi.img.xz"}' dietpi.img.xz.sha256) )

if [ -f "$work/dietpi.img.xz.asc" ]; then
  echo "==> Verifying PGP signature against DietPi's published keyring"
  curl -sSL -o "$work/dietpi.gpg" "$KEYRING_URL"
  gpg --no-default-keyring --keyring "$work/dietpi.gpg" --verify "$work/dietpi.img.xz.asc" "$work/dietpi.img.xz"
fi

echo "==> Extracting DietPi version (for the release tag)"
docker build -q -t rpi-airplay-image-builder -f Dockerfile.image-builder . >/dev/null
xz -dk "$work/dietpi.img.xz" -c > "$work/dietpi.img"
docker run --rm -v "$work":/w rpi-airplay-image-builder \
  bash /w/../image-builder/extract-partitions.sh /w/dietpi.img /w/peek-boot /w/peek-root 2>/dev/null || true
# .version lives in the root partition at /boot/dietpi/.version (DietPi's
# own housekeeping path, distinct from /boot/firmware -- the FAT32 RPi
# bootloader partition, which extract-partitions.sh calls "boot").
VERSION=$(docker run --rm -v "$work":/w rpi-airplay-image-builder \
  cat /w/peek-root/boot/dietpi/.version 2>/dev/null | tr '\n' '-' | sed 's/-$//' || echo "unknown")
DIETPI_VER="dietpi-base-v${VERSION:-unknown}-$(date +%Y%m%d)"
echo "  version tag: $DIETPI_VER"

SHA256=$(sha256sum "$work/dietpi.img.xz" | cut -d' ' -f1)

echo "==> Publishing GitHub Release $DIETPI_VER on $REPO"
gh release create "$DIETPI_VER" "$work/dietpi.img.xz" \
  --repo "$REPO" \
  --title "DietPi base image: $DIETPI_VER" \
  --notes "Re-hosted, verified copy of $URL (sha256-and-PGP-checked against DietPi's own published values at download time). See image-builder/BASE-IMAGE.env and vendor/gstreamer-1.0-arm64-trixie/MANIFEST.md for why this project vendors its own copy instead of depending on dietpi.com's mutable download page."

RELEASE_URL="https://github.com/$REPO/releases/download/$DIETPI_VER/dietpi.img.xz"
cat > image-builder/BASE-IMAGE.env <<EOF
# Auto-generated by image-builder/refresh-base-image.sh -- do not edit by hand.
# Pinned, versioned copy of DietPi's RPi 2/3/4 arm64 trixie image, re-hosted
# because DietPi itself has no versioned archive (see this file's generator
# script for the full rationale). Regenerate via 'make refresh-base-image'.
BASE_IMAGE_URL="$RELEASE_URL"
BASE_IMAGE_SHA256="$SHA256"
BASE_IMAGE_DIETPI_VERSION="$VERSION"
EOF

echo "==> Pinned. image-builder/BASE-IMAGE.env updated -- commit it."
